baseURL = "http://example.org/"
languageCode = "en-us"
title = "Nick Frosst's personal site"
theme = "book"
BookMenuBundle = "/menu" 
[params]
    BookSearch = "false"
    body_classes = "avenir bg-near-white"
 